name: Deploy Web Presensi

on:
    push:
        branches:
            - main

jobs:
    web-deploy:
        name: SSH-Deploy-Action
        runs-on: ubuntu-latest
        steps:
            # Setup SSH Key
            - name: Set up secret file
              env:
                  ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
              run: |
                  echo "$ssh-key" > secrets.txt
                  chmod 600 secrets.txt
                  echo "SSH key set up successfully."

            # Checkout source code
            - name: Checkout
              uses: actions/checkout@v4

            # Debug root files
            - name: Debug root files
              run: ls -la

            # Debug frontend folder files
            - name: Debug frontend files
              working-directory: ./frontend
              run: ls -la

            # Cache Node Modules
            - name: Cache Node Modules
              uses: actions/cache@v3
              with:
                  path: ./frontend/node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-${{ github.run_id }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            # Set up Node.js environment
            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"

            # Install project dependencies
            - name: Install dependencies
              working-directory: ./frontend
              run: npm ci

            # Debug node_modules
            - name: Debug node_modules
              working-directory: ./frontend
              run: ls -la node_modules

            # Cache Build Output
            - name: Cache Build Output
              uses: actions/cache@v3
              with:
                  path: ./frontend/dist
                  key: build-output-${{ github.sha }}

            # Build the project
            - name: Build
              working-directory: ./frontend
              run: npm run build -- --mode production

            # Deploy built files to the server
            - name: Deploy
              uses: SamKirkland/web-deploy@v1
              with:
                  target-server: 23.106.52.199
                  remote-user: smalabsc
                  private-ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
                  destination-path: ~/smartapps.smalabschoolunesa1.sch.id/frontend/
                  source-path: ./frontend
                  ssh-port: 45022
                  overwrite: false
                  only-changed-files: true
