name: Deploy Web Presensi

on:
    push:
        branches:
            - main

jobs:
    web-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Set up secret file
              env:
                  ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
              run: echo "$ssh-key" >> secrets.txt

            - name: Checkout source code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Detect changes in frontend
              id: check_changes
              run: |
                  if git diff --name-only HEAD~1 HEAD | grep -qE '^frontend/'; then
                    echo "changed=true" >> $GITHUB_ENV
                  else
                    echo "changed=false" >> $GITHUB_ENV
                  fi

            - name: Stop if no changes
              if: ${{ env.changed == 'false' }}
              run: echo "No changes in frontend, stopping pipeline..." && exit 0

            - name: Cache Node Modules
              uses: actions/cache@v3
              with:
                  path: ./frontend/node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/frontend/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-
              if: ${{ env.changed == 'true' }}

            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"
                  cache-dependency-path: ./frontend/package-lock.json
              if: ${{ env.changed == 'true' }}

            - name: Install dependencies
              working-directory: ./frontend
              run: npm ci
              if: ${{ env.changed == 'true' }}

            - name: Cache Build
              uses: actions/cache@v3
              with:
                  path: ./frontend/dist
                  key: ${{ runner.os }}-build-${{ hashFiles('**/frontend/src/**/*', '**/frontend/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-
              if: ${{ env.changed == 'true' }}

            - name: Build the frontend
              working-directory: ./frontend
              run: npm run build
              if: ${{ env.changed == 'true' }}

            - name: Deploy
              uses: SamKirkland/web-deploy@v1
              with:
                  target-server: 23.106.52.199
                  remote-user: smalabsc
                  private-ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
                  destination-path: ~/smartapps.smalabschoolunesa1.sch.id/
                  source-path: ./frontend/dist
                  ssh-port: 45022
                  delete-remote: true
                  only-changes: true
