name: Deploy Web Presensi

on:
    push:
        branches:
            - main

jobs:
    web-deploy:
        runs-on: ubuntu-latest
        steps:
            # Checkout source code with full history
            - name: Checkout source code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Pastikan seluruh riwayat commit tersedia

            # Detect changes in frontend
            - name: Detect changes in frontend
              id: check_changes
              run: |
                  git diff --name-only HEAD~1 HEAD | grep -E '^frontend/' || echo "No changes in frontend"
                  if [[ $(git diff --name-only HEAD~1 HEAD | grep -E '^frontend/') ]]; then
                    echo "changed=true" >> $GITHUB_ENV
                  else
                    echo "changed=false" >> $GITHUB_ENV
                  fi

            # Cache Node Modules
            - name: Cache Node Modules
              uses: actions/cache@v3
              with:
                  path: ./frontend/node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/frontend/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-
              if: env.changed == 'true'

            # Set up Node.js environment
            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"
                  cache-dependency-path: ./frontend/package-lock.json
              if: env.changed == 'true'

            # Install project dependencies
            - name: Install dependencies
              working-directory: ./frontend
              run: npm ci
              if: env.changed == 'true'

            # Build the project
            - name: Build the frontend
              working-directory: ./frontend
              run: npm run build
              if: env.changed == 'true'

            # Deploy built files to the server
            - name: Deploy
              uses: SamKirkland/web-deploy@v1
              with:
                  target-server: 23.106.52.199
                  remote-user: smalabsc
                  private-ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
                  destination-path: ~/smartapps.smalabschoolunesa1.sch.id/
                  source-path: ./frontend/dist/
                  ssh-port: 45022
              if: env.changed == 'true'
