name: Deploy Web Presensi

on:
    push:
        branches:
            - main

jobs:
    web-deploy:
        name: SSH-Deploy-Action
        runs-on: ubuntu-latest
        steps:
            - name: Set up secret file
              env:
                  ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
              run: |
                  echo "$ssh-key" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  cache-dependency-path: ./frontend/package-lock.json
                  node-version: 20
                  cache: "npm"
            - name: Install dependencies
              working-directory: ./frontend
              run: npm ci
            - name: Build
              working-directory: ./frontend
              run: npm run build
            - name: Rename build directory
              working-directory: ./frontend
              run: mv dist build
            - name: Deploy
              uses: SamKirkland/web-deploy@v1
              with:
                  target-server: 23.106.52.199
                  remote-user: smalabsc
                  private-ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
                  destination-path: ~/smartapps.smalabschoolunesa1.sch.id/
                  source-path: ./frontend/build
                  ssh-port: 45022
