name: Deploy Web Presensi

on:
    push:
        branches:
            - main

jobs:
    web-deploy:
        runs-on: ubuntu-latest
        steps:
            # Checkout source code
            - name: Checkout
              uses: actions/checkout@v4

            # Detect changes in frontend
            - name: Check for changes in frontend
              id: check_changes
              run: |
                  git diff --exit-code --quiet ./frontend || echo "Frontend files have changed"

            # Cache Node Modules
            - name: Cache Node Modules
              uses: actions/cache@v3
              with:
                  path: ./frontend/node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/frontend/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            # Set up Node.js environment
            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"
                  cache-dependency-path: ./frontend/package-lock.json

            # Install project dependencies
            - name: Install dependencies
              working-directory: ./frontend
              run: npm ci
              if: steps.check_changes.outputs.changed == 'true'

            # Cache Build Output
            - name: Cache Build Output
              uses: actions/cache@v3
              with:
                  path: ./frontend/dist
                  key: build-output-${{ github.sha }}
              if: steps.check_changes.outputs.changed == 'true'

            # Build the project
            - name: Build
              working-directory: ./frontend
              run: npm run build
              if: steps.check_changes.outputs.changed == 'true'

            # Set up SSH key for deployment
            - name: Set up SSH key
              run: |
                  mkdir -p ~/.ssh
                  echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan -t rsa 23.106.52.199 >> ~/.ssh/known_hosts

            # Ensure the target folder exists on the server
            - name: Ensure frontend directory exists
              run: |
                  ssh -i ~/.ssh/id_rsa smalabsc@23.106.52.199 "mkdir -p ~/smartapps.smalabschoolunesa1.sch.id/frontend"

            # Deploy built files to the server using rsync
            - name: Deploy with rsync
              run: |
                  rsync -avz --delete ./frontend/dist/ smalabsc@23.106.52.199:~/smartapps.smalabschoolunesa1.sch.id/frontend/
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
              if: steps.check_changes.outputs.changed == 'true'
